# Generated by Django 3.2.12 on 2022-06-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.racecar')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourneys.race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='racers',
            field=models.ManyToManyField(through='tourneys.TimeTrial', to='racers.RaceCar'),
        ),
        migrations.AddField(
            model_name='race',
            name='tourney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourneys.tournament'),
        ),
    ]
