# Generated by Django 3.2.12 on 2022-06-12 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrial',
            name='lane',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetrial',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
