# Generated by Django 3.2.12 on 2022-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0002_auto_20220612_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
