# Generated by Django 3.2.12 on 2022-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0003_alter_race_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrial',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
