# Generated by Django 3.2.12 on 2022-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0004_alter_timetrial_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetrial',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
