# Generated by Django 3.2.12 on 2022-06-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
        ('tourneys', '0005_auto_20220612_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.racecar')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourneys.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_cars',
            field=models.ManyToManyField(through='tourneys.Registration', to='racers.RaceCar'),
        ),
    ]
