# Generated by Django 3.2.12 on 2022-06-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
        ('tourneys', '0007_auto_20220620_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='racers',
            field=models.ManyToManyField(related_name='races', through='tourneys.TimeTrial', to='racers.RaceCar'),
        ),
    ]
