# Generated by Django 3.2.12 on 2022-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0008_alter_race_racers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
