# Generated by Django 3.2.12 on 2022-06-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0009_alter_race_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetrial',
            name='end_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetrial',
            name='mid_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
